name: HelloWorld
version: 1.0
author: kaua
main: kaua.studies.helloworld.Main
description: My first Minecraft Spigott plugin

commands:
  hello:
   aliases: [hi]
   description: This is the hello command