name: kaua
description: Tutorial with mclovin
version: 1.0
api-version: 1.16
main: kaua.studies.tutorial.Main

commands:
  test:
    aliases: [testcommand]
    description: test command made by mclovin series